# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 05:02
from __future__ import unicode_literals

import common.utils.common_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spoonhunt', '0073_auto_20171110_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('object_id', models.UUIDField(default=common.utils.common_utils.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name=b'Last update time')),
                ('enabled', models.BooleanField(default=True, verbose_name=b'Is active?')),
                ('name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active')], default=1)),
                ('token', models.CharField(max_length=200)),
                ('udid', models.CharField(max_length=200)),
                ('platform', models.IntegerField(choices=[(3, 'Web'), (1, 'iOS'), (2, 'Android')], default=1)),
                ('last_login', models.DateTimeField(null=True)),
                ('lang_code', models.CharField(blank=True, max_length=200, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoonhunt.User')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Device',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('object_id', models.UUIDField(default=common.utils.common_utils.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name=b'Last update time')),
                ('enabled', models.BooleanField(default=True, verbose_name=b'Is active?')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_success', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Device')),
            ],
            options={
                'verbose_name': 'Push',
                'verbose_name_plural': 'Push',
            },
        ),
    ]
